name: Publish Kavita.ReleaseTools to NuGet

on:
  push:
    branches: ["main"]
    paths: ["Kavita.ReleaseTools/**", ".github/workflows/release-kavita-release-tools.yml"]

permissions:
  id-token: write
  contents: write
  pull-requests: read

jobs:
  run-release-tool:
    uses: "./.github/workflows/release-tools.base.yml"
    secrets: inherit
    with:
      config-path: "release.yaml"
